name: Data cleanup
on:
    schedule:
        - cron: '30 5 * * 5'
        # runs every friday 1100 IST 0530 UTC
jobs:
    clean-gratitudes:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v3
            -   name: Install NodeJs
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.npm
                    key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install dependencies
                run: npm ci
            -   name: Cleanup gratitudes
                run: npm run clean-gratitudes "${{ secrets.FIREBASE_USER_NAME }}" "${{ secrets.FIREBASE_SERVICE_PWD }}"
            -   name: Echo status
                run: echo 'Build completed successfully.'
    
    clean-images:
        needs: clean-gratitudes
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v3
            -   name: Install NodeJs
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.npm
                    key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install dependencies
                run: npm ci
            -   name: Cleanup images
                run: npm run clean-images "${{ secrets.FIREBASE_USER_NAME }}" "${{ secrets.FIREBASE_SERVICE_PWD }}"
            -   name: Echo status
                run: echo 'Build completed successfully.'

